### ISSUE TITLE
Correcting for day-of-week reporting artifacts?

### ISSUE THREAD

**Issue by JonasHeidelberg** [cjolowicz/covid19#1]
Hi, thanks for this cool animated gif graphic! I haven't understood yet how you calculate it - is it purely based on the numbers in rki.py? 

If so, what do you think about correcting for the day-of-week pattern visible in the bottom right "cases/day" curve in https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4/page/page_0/ ? I am certain this is an artifact of how the data is collected, not of the underlying dynamics of actual infections. It appears to drive some of the "back and forth" in your gif... so this correction could make your simulation more stable and reliable...

**Comment by cjolowicz** [comment]
Thank you for the feedback @JonasHeidelberg !

Yes, it would make sense to correct for the day-of-week pattern. Currently, the code uses the geometric mean over the growth rate of the last 5 days. I guess that should mitigate this problem a little bit. 

I'm not sure when I will be able to fix this properly. This is a side project out of interest, so unfortunately I cannot spend a lot of time on it. But I'm very interested to hear about ways it could be improved, so thank you again!

If you're interested in how the calculations are done, have a look at the [simulation](../blob/master/src/covid19/simulation.py) module, in particular the `Simulation.step` function. This calculates the new infections based on the growth rate (see above), as well as the number of active cases and the number of immune persons on the previous day.

```python
        immunization: float = self.state.immune / self.population
        prevalence: float = self.state.cases / self.population
        infections: int = int(
            self.state.cases
            * self.state.probability
            * (1 - (prevalence + immunization))
        )
```

The simulation assumes a fixed case duration of 14 days to calculate recoveries.

It is a simplistic model, and meant to understand the dynamics of this a little bit better, rather than intended to produce solid and accurate predictions.

There are different data sources available, but [rki.py](../blob/master/src/covid19/data/rki.py) is used by default.

**Comment by JonasHeidelberg** [comment]
Thanks for the explanation! How about averaging the last 7 rather than 5 days, as a quick fix? This way you always include data from each weekday in your average?

**Comment by cjolowicz** [comment]
Yes, here: 9a822df6c097cbaa28d700aebc6ec014fefea8a7

**Comment by JonasHeidelberg** [comment]
Thanks, nice! 

By eye, it seems to reduce the oscillating in your animated gif - of course more averaging will always do that, so one could check if it gets worse again when averaging 8 days. If I have lots of time over Easter I might have a look. Otherwise, thanks for the discussion :-).

Should we close this for now?

**Comment by cjolowicz** [comment]
Your feedback is very appreciated :-)

I'm closing this now. Feel free to comment here or in another issue, if you find more things that can be improved.
